name: Deploy to AWS CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ASIA4XNIDHVV5MRZTT73
        aws-secret-access-key: llKwm1q01wH1KvTqBJVyg2nFZAki3pOlInrGb098
        aws-session-token: ${{ secrets.TOKEN_AWS}}
        aws-region: us-east-1  # Change to your region

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name MedEquipStack \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides \
            DBUsername=${{ secrets.DB_USERNAME }} \
            DBPassword=${{ secrets.DB_PASSWORD }} \
            KeyName=${{ secrets.KEY_NAME }}
