name: Deploy Full AWS Infrastructure to CloudFormation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Delete Failed Stack if in ROLLBACK_COMPLETE
        continue-on-error: true
        run: |
          status=$(aws cloudformation describe-stacks --stack-name MedEquipStack --query "Stacks[0].StackStatus" --output text)
          if [ "$status" = "ROLLBACK_COMPLETE" ]; then
            echo "Deleting failed stack..."
            aws cloudformation delete-stack --stack-name MedEquipStack
          fi

      - name: Deploy VPC Stack (404AZStack.yaml)
        run: |
          aws cloudformation deploy \
            --template-file 404AZStack.yaml \
            --stack-name MedEquipStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset \
            --parameter-overrides SshCidr=0.0.0.0/0

      - name: Debug VPC Stack if Failed
        if: failure()
        run: |
          echo "❌ VPC Stack Deployment Failed"
          aws cloudformation describe-stack-events --stack-name MedEquipStack \
            --max-items 10 | jq -r '.StackEvents[] | "\(.LogicalResourceId): \(.ResourceStatus) - \(.ResourceStatusReason // "N/A")"'

      - name: Deploy EC2 Stack (instances.yaml)
        run: |
          aws cloudformation deploy \
            --template-file instances.yaml \
            --stack-name MedEquipEC2Stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Debug EC2 Stack if Failed
        if: failure()
        run: |
          echo "❌ EC2 Stack Deployment Failed"
          aws cloudformation describe-stack-events --stack-name MedEquipEC2Stack \
            --max-items 10 | jq -r '.StackEvents[] | "\(.LogicalResourceId): \(.ResourceStatus) - \(.ResourceStatusReason // "N/A")"'
